[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"